name: todos
description: An example todos app built with Dart Frog.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_frog: ^1.0.0
  mongo_dart: ^0.8.2
  todos_data_source:
    path: packages/todos_data_source

dev_dependencies:
  http: ^1.0.0
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0